server:
  port: 8080

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://db.rlmyzcpeygndbmiwnvjo.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: Duynien123@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

cloudinary:
  cloud-name: dqbhgxlyx
  api-key: 696626117536851
  api-secret: y3p-jAPZIFzSOsIDIMeQv4Bg1pY
unsplash:
  access-key: ZHlnokAphfexz7xjHVKpKrbc_Bh3LqV1ppatzFhAt7E
  base-url: https://api.unsplash.com

